# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EasyImport
                                 A QGIS plugin
 This plugins enables easy GPS codification to any layer destination
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-22
        copyright            : (C) 2018 by Xavier Ménétrey et Arnaud Poncet-Montanges / Ville de Pully
        email                : informatique@pully.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EasyImport class from file EasyImport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .easyimport import EasyImport
    return EasyImport(iface)
